FROM node:10-slim as prod

ENV NODE_ENV=production
COPY package*.json ./
# production comes from the package.json file declarations.
RUN npm install --only=production && npm cache clean --force
COPY . .
CMD [ "node", "./bin/www" ]

# Dev is local development environment, won't be pushed to a registry.
FROM prod as dev
ENV NODE_ENV=development
#Install Dev Dependencies
RUN npm install --only=development
# Dev will chnage the CMD
CMD [ "node", "../node_modules/nodemon/bin/nodemon.js", "./bin/www", "--inspect=0.0.0.0:922" ]

# This phase is for demo purposes as we would traditionally run this from a docker-compse file.
# This is great for CI like Jenkins
FROM dev as test
ENV NODE_ENV=development
#RUN npm test  <- You can also run the command this way
CMD [ "npm", "test" ]